configfile: "config/config.yaml"

import requests
import logging as log
import polars as pl
import spirepy

ITEM_ID = config["item"]

def find_item_type(item_id):
    study_response = requests.get(f"https://spire.embl.de/spire/api/study/{item_id}")
    sample_response = requests.get(f"https://spire.embl.de/spire/api/sample/{item_id}")

    if len(study_response.content) > 3:
        return "study"
    elif len(sample_response.content) > 3:
        return "sample"
    else:
        raise ValueError(f"Item {item_id} not found on SPIRE.")


ITEM_TYPE = find_item_type(ITEM_ID)

if ITEM_TYPE == "study":
    study = spirepy.Study(ITEM_ID)
    SAMPLES = [s.id for s in study.get_samples()]
    MAGS = study.get_mags()["genome_id"].to_list()
elif ITEM_TYPE == "sample":
    SAMPLES = [ITEM_ID]
    sample = spirepy.Sample(ITEM_ID)
    MAGS = sample.get_mags()["genome_id"].to_list()
else:
    raise ValueError("Unknown item type")

print("Samples to process:", SAMPLES)
print("MAGS to process:", MAGS)

rule all:
    input:
        "results/manifest.csv",
        expand("results/reconstructions/{mag}.xml", mag=MAGS),
        "results/.mags.cleaned",
        "results/exchanges.csv",
        "results/growth_rates.csv",
        "results/interactions.csv"

rule download_mags:
    output:
        "results/mags/{mag}.fa.gz"
    shell:
        "wget -O {output} https://spire.embl.de/download_file/{wildcards.mag}"

rule generate_sample_manifest:
    output:
        temp("results/manifests/{sample}.csv")
    shell:
        "python scripts/generate_sample_manifest.py {wildcards.sample} {output}"

rule combine_manifests:
    input:
        expand("results/manifests/{sample}.csv", sample=SAMPLES)
    output:
        "results/manifest.csv"
    shell:
        "python scripts/combine_manifests.py {output} {input}"

rule reconstruct:
    input:
        expand("results/mags/{mag}.fa.gz", mag=MAGS)
    output:
        "results/reconstructions/{mag}.xml"
    shell:
        "carve --dna {input} -g M9 --output {output}"

rule cleanup_mags:
    input:
        "results/manifest.csv"
    output:
        touch("results/.mags.cleaned")
    run:
        import os
        for mag in MAGS:
            p = f"results/mags/{mag}.fa.gz"
            if os.path.exists(p):
                os.remove(p)
        open(output[0], "w").close()

rule simulate:
    input:
        "results/manifest.csv"
    output:
        "results/exchanges.csv",
        "results/growth_rates.csv",
        "results/interactions.csv"
    shell:
        "python scripts/simulate.py {input}"
